name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
    CI:
        runs-on: ubuntu-latest

        permissions:
          contents: read # Needed to clone the repository

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
 
        - name: Install miniconda 24.11.1
          run: |
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-py312_24.5.0-0-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm ~/miniconda3/miniconda.sh

        - name: Set up Enviroment
          run: |
            conda init tango_with_django
            conda activate tango_with_django
            
        - name: Install Python 3.11.11
          uses: actions/setup-python@v3
          with:
            python-version: '3.11.11'

        - name: Install Dependancies
          run: |
            pip freeze > requirements.txt
            pip install -r requirements.txt 

        - name: Run test(chapter 3)
          run: python manage.py test rango.tests_chapter3
