name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
    CI:
        runs-on: ubuntu-latest

        permissions:
          contents: read # Needed to clone the repository

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
 
        - name: Install miniconda 24.11.1
          uses: conda-incubator/setup-miniconda@v3
          with:
            miniconda-version: "24.11.1"

        - name: Set up Enviroment
          run: |
            conda init --all
            conda activiate tango_with_django
            
        - name: Install Python 3.11.11
          uses: actions/setup-python@v3
          with:
            python-version: '3.11.11'

        - name: Install Dependancies
          run: |
            pip freeze > requirements.txt
            pip install -r requirements.txt 

        - name: Run test(chapter 3)
          run: python manage.py test rango.tests_chapter3
